// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SkillTree","status":true,"description":"スキルツリー v1.6.4","parameters":{"SpName":"SP","MaxSp":"9999","EnabledSkillTreeSwitchId":"0","EnableGetSpWhenBattleEnd":"true","EnableGetSpWhenLevelUp":"true","ViewMode":"long","EnableMZLayout":"false","IconWidth":"128","IconHeight":"32","IconSpaceWidth":"16","IconSpaceHeight":"48","ViewLineWidth":"2","ViewLineColorBase":"#000000","ViewLineColorLearned":"#00aaff","ViewBeginXOffset":"24","ViewBeginYOffset":"24","ViewCursorOfs":"8","ViewRectColor":"#ffff00","ViewRectOfs":"0","LearnSkillSeFileName":"Item3","LearnSkillSeVolume":"90","LearnSkillSePitch":"100","LearnSkillSePan":"0","MenuSkillTreeText":"スキルツリー","NeedSpText":"必要%1：","OpenedNodeText":"取得済み","NodeOpenConfirmationText":"%1%2を消費して%3を取得しますか？","NodeOpenYesText":"習得する","NodeOpenNoText":"習得しない","BattleEndGetSpText":"%1%2を入手した。","LevelUpGetSpText":"%1%2を入手した。"}},
{"name":"SkillTreeConfig","status":true,"description":"スキルツリーコンフィグ","parameters":{}},
{"name":"SkillTree_LayoutEx","status":true,"description":"スキルツリー レイアウト拡張 v1.2.3","parameters":{"IconXOfs":"5","OpenedImage":"{\"EnableOpenedImage\":\"false\",\"FileName\":\"pictures/rect\",\"XOfs\":\"0\",\"YOfs\":\"0\"}","ChangeOpenedTextColor":"true","IconFontSize":"20","BackgroundImage":"{\"FileName\":\"\",\"BackgroundImage2\":\"[]\",\"BackgroundImage2XOfs\":\"240\",\"BackgroundImage2YOfs\":\"300\"}"}},
{"name":"AutoPluginUpdater","status":true,"description":"プラグイン自動更新プラグイン v1.0.0","parameters":{"BackupDirName":"backup","PluginUrl":"[]","DisableUpdatePlugin":"[\"SkillTreeConfig\"]","WriteLog":"true","LogFileName":"plugin-update-log.txt","TimestampFileName":"plugin-update-timestamp.json"}}
];
